---
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaphcrew/spring-config-server
          searchPaths: email-service,order-service
server:
  port: 8888
